services:
  - type: web
    name: symmetry-detection
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:10000 app:app
    instanceType: micro
